# Generated by Django 5.1.7 on 2025-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcomment',
            name='batchname',
            field=models.CharField(default='def', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
