# Generated by Django 5.1.7 on 2025-03-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_batchcomment_batchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcomment',
            name='batchname',
            field=models.CharField(max_length=30),
        ),
    ]
